# Run with docker compose up
version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/data:/var/lib/mysql"
  echo1:
    image: echo1:latest
    depends_on:
      - mysql
    environment:
      MICRONAUT_ENVIRONMENTS: cloud
      DATASOURCES_DEFAULT_USERNAME: root
      DATASOURCES_DEFAULT_PASSWORD: password
      DATASOURCES_DEFAULT_URL: jdbc:mysql://mysql:3306/db
  echo2:
    image: echo2:latest
    depends_on:
      - mysql
    environment:
      MICRONAUT_ENVIRONMENTS: cloud
      DATASOURCES_DEFAULT_USERNAME: root
      DATASOURCES_DEFAULT_PASSWORD: password
      DATASOURCES_DEFAULT_URL: jdbc:mysql://mysql:3306/db
  restaurant:
    image: restaurant:latest
    depends_on:
      - mysql
    environment:
      MICRONAUT_ENVIRONMENTS: cloud
      DATASOURCES_DEFAULT_USERNAME: restaurant
      DATASOURCES_DEFAULT_PASSWORD: restaurant
      DATASOURCES_DEFAULT_URL: jdbc:mysql://mysql:3306/restaurant
  nginx:
    image: nginx:1.23.2
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx:/data/www"