micronaut:
  application:
    name: echo1
  server:
    cors:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql