import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import io.micronaut.gradle.docker.MicronautDockerfile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 *
 * Dependencies updated using https://micronaut.io/launch
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.21"
    id("org.jetbrains.kotlin.kapt") version "1.6.21"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.6.21"

    id("com.github.johnrengelman.shadow") version "7.1.2"

    id("io.micronaut.application") version "3.6.2"
    id("io.micronaut.test-resources") version "3.6.2"
}

version = "0.1"
group = "io.resto"

val kotlinVersion = project.properties["kotlinVersion"]

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")

    // Minimal Micronaut dependencies
    kapt("io.micronaut:micronaut-http-validation")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("jakarta.annotation:jakarta.annotation-api")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")

    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")

    // Database connection
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    runtimeOnly("mysql:mysql-connector-java")
}

application {
    // Define the main class for the application.
    mainClass.set("io.resto.echo1.Echo1AppKt")
}

java {
    sourceCompatibility = JavaVersion.toVersion("11")
}

tasks {
    compileKotlin {
        kotlinOptions {
            jvmTarget = "11"
        }
    }
    compileTestKotlin {
        kotlinOptions {
            jvmTarget = "11"
        }
    }
}
graalvmNative.toolchainDetection.set(false)
micronaut {
    version("3.7.2")
    runtime("netty")
    testRuntime("kotest5")
    processing {
        incremental(true)
        annotations("io.resto.*")
    }
    testResources {
        additionalModules.add("jdbc-mysql")
    }
}

// See https://micronaut-projects.github.io/micronaut-gradle-plugin/snapshot/#_docker_support
tasks.named<MicronautDockerfile>("dockerfile") {
    // baseImage.set("eclipse-temurin:11")
    baseImage.set("gcr.io/distroless/java11-debian11")
    args("-Xmx128m")
}

tasks.named<DockerBuildImage>("dockerBuild") {
    // TODO specify docker repo here
    // images.add("eu-frankfurt-1.ocir.io/xyzzyz/repo/my-image:$project.version")
}